# Generated by Django 5.2.3 on 2025-06-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='set',
        ),
    ]
