# Generated by Django 5.2.3 on 2025-06-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sets'),
        ),
    ]
