# Generated by Django 5.2.3 on 2025-06-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_set_alter_product_set_delete_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='set',
        ),
    ]
