# Generated by Django 5.2.3 on 2025-06-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
