# Generated by Django 5.2.3 on 2025-06-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShippingAddress',
            new_name='shipping_address',
        ),
    ]
