# Generated by Django 5.2.3 on 2025-06-25 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_date_shipped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions (optional, max 500 characters)', max_length=500, null=True, verbose_name='Delivery Instructions'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for delivery (optional)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(help_text='Street address, P.O. box, or company name', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc. (optional)', max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(help_text='City or town', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='GB', help_text='Two-letter country code (ISO 3166-1)', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_county',
            field=models.CharField(help_text='County, state, or region', max_length=50, verbose_name='County/State'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(help_text='Email for delivery notifications', max_length=254),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(help_text='Full name for delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_postcode',
            field=models.CharField(help_text='Postal code or ZIP code', max_length=12, verbose_name='Postal Code'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'updated_at'], name='payment_shi_user_id_de73f0_idx'),
        ),
    ]
