# Generated by Django 5.2.3 on 2025-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='United Kingdom', help_text='Country name', max_length=100, verbose_name='Country'),
        ),
    ]
