from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.control_panel_home,
        name='control_panel_home'
    ),
    path(
        'orders/',
        views.orders,
        name='control_panel_orders'
    ),
    path(
        'orders/<int:order_id>/',
        views.order_detail,
        name='control_panel_order_detail'
    ),
    path(
        'orders/mark_shipped/<int:order_id>/',
        views.mark_order_shipped,
        name='control_panel_mark_order_shipped'
    ),
    path(
        'products/',
        views.products,
        name='control_panel_products'
    ),
    path(
        'products/add/',
        views.add_product,
        name='control_panel_add_product'
    ),
    path(
        'edit_product/<int:product_id>/',
        views.edit_product,
        name='control_panel_edit_product'
    ),
    path(
        'delete_product/<int:product_id>/',
        views.confirm_delete_product,
        name='confirm_delete_product'
    ),
    path(
        'manage_categories/',
        views.manage_categories,
        name='control_panel_manage_categories'
    ),
    path(
        'add_category/',
        views.add_category,
        name='control_panel_add_category'
    ),
    path(
        'edit_category/<int:category_id>/',
        views.edit_category,
        name='control_panel_edit_category'
    ),
    path(
        'delete_category/<int:category_id>/',
        views.confirm_delete_category,
        name='confirm_delete_category'
    ),
    path(
        'manage_sets/',
        views.manage_sets,
        name='control_panel_manage_sets'
    ),
    path(
        'manage_sets/add_set/',
        views.add_set,
        name='control_panel_add_set'
    ),
    path(
        'manage_sets/edit_set/<int:set_id>/',
        views.edit_set,
        name='control_panel_edit_set'
    ),
    path(
        'manage_sets/delete_set/<int:set_id>/',
        views.confirm_delete_set,
        name='confirm_delete_set'
    ),
    path(
        'manage_reviews/',
        views.manage_reviews,
        name='control_panel_manage_reviews'
    ),
    path(
        'toggle_review_status/<int:review_id>/',
        views.toggle_review_status,
        name='control_panel_toggle_review_status'
    ),
    path(
        'confirm_delete_review/<int:review_id>/',
        views.confirm_delete_review,
        name='confirm_delete_review'
    )
]
